import typography from '@tailwindcss/typography';

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'secondary-fixed': '#bcf540',
        'on-surface': '#171d19',
        'on-error-container': '#93000a',
        'outline-variant': '#c2c8c2',
        'inverse-on-surface': '#ecf2ec',
        'surface-container-highest': '#dee4de',
        'surface-container-low': '#eff5ef',
        'error-container': '#ffdad6',
        'on-secondary-fixed-variant': '#374e00',
        'inverse-primary': '#b1cdbb',
        'tertiary-fixed-dim': '#c5c7c5',
        'surface-container-high': '#e4eae4',
        'on-tertiary': '#ffffff',
        'primary-fixed-dim': '#b1cdbb',
        'on-background': '#171d19',
        outline: '#727973',
        'surface-container': '#e9efe9',
        'on-error': '#ffffff',
        'primary-fixed': '#cde9d6',
        'secondary-fixed-dim': '#a1d820',
        'on-secondary-fixed': '#141f00',
        'on-primary-fixed': '#072014',
        'on-tertiary-fixed': '#191c1b',
        'on-tertiary-container': '#858886',
        'secondary-container': '#bcf540',
        secondary: '#4a6700',
        'on-primary-container': '#b1cdbb',
        'inverse-surface': '#2c322e',
        'surface-container-lowest': '#ffffff',
        'surface-bright': '#f5fbf5',
        tertiary: '#050807',
        'on-tertiary-fixed-variant': '#444746',
        'on-surface-variant': '#424844',
        'on-secondary': '#ffffff',
        'tertiary-fixed': '#e1e3e1',
        'surface-dim': '#d5dcd6',
        'surface-variant': '#dee4de',
        'tertiary-container': '#1d201f',
        'surface-tint': '#4a6455',
        primary: '#000a04',
        'on-secondary-container': '#4f6e00',
        surface: '#f5fbf5',
        background: '#f5fbf5',
        'on-primary': '#ffffff',
        'primary-container': '#0b2418',
        'on-primary-fixed-variant': '#334c3e',
        error: '#ba1a1a',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'stack-lg': '48px',
        gutter: '24px',
        'container-max': '1280px',
        'stack-md': '24px',
        unit: '8px',
        'section-padding': '80px',
        'stack-sm': '12px',
      },
      fontFamily: {
        'body-md': ['Manrope', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        'body-lg': ['Manrope', 'sans-serif'],
        h2: ['Manrope', 'sans-serif'],
        h1: ['Manrope', 'sans-serif'],
        display: ['Manrope', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        h2: ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        h1: ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        display: ['clamp(2.75rem, 7vw, 4.75rem)', { lineHeight: '1.05', letterSpacing: '-0.035em', fontWeight: '700' }],
      },
    },
  },
  plugins: [typography],
};
